#!/usr/bin/env python3
"""
Convert MS SQL Server DDL script to PostgreSQL DDL script - Version 2
Simplified and more robust converter.
"""

import re
import sys


def convert_sql_to_postgresql(input_file, output_file):
    """Convert SQL Server script to PostgreSQL."""
    
    print(f"Reading from: {input_file}")
    
    # Try different encodings
    content = None
    for encoding in ['utf-16-le', 'utf-16', 'utf-8', 'utf-8-sig', 'cp1252', 'latin1']:
        try:
            with open(input_file, 'r', encoding=encoding) as f:
                content = f.read()
            print(f"Successfully read with encoding: {encoding}")
            break
        except (UnicodeDecodeError, UnicodeError):
            continue
    
    if content is None:
        print("ERROR: Could not read file with any encoding")
        return False
    
    lines = content.split('\n')
    output_lines = []
    
    # Header
    output_lines.append('-- PostgreSQL DDL converted from MS SQL Server')
    output_lines.append('-- Generated by xPort5.Pgsql schema converter v2')
    output_lines.append('-- NOTE: Stored procedures require manual review and conversion')
    output_lines.append('')
    output_lines.append('BEGIN;')
    output_lines.append('')
    
    in_create_table = False
    in_procedure = False
    skip_next_lines = 0
    
    for i, line in enumerate(lines):
        if skip_next_lines > 0:
            skip_next_lines -= 1
            continue
            
        line_upper = line.upper().strip()
        
        # Skip lines
        if line_upper.startswith('USE '):
            continue
        if line_upper == 'GO':
            if in_create_table:
                in_create_table = False
            if in_procedure:
                in_procedure = False
            continue
        if 'SET ANSI_NULLS' in line_upper or 'SET QUOTED_IDENTIFIER' in line_upper:
            continue
        if 'EXEC SYS.SP_ADDEXTENDEDPROPERTY' in line_upper or 'SP_ADDEXTENDEDPROPERTY' in line_upper:
            continue
        if line_upper.startswith('ALTER TABLE') and 'CHECK CONSTRAINT' in line_upper and 'ADD' not in line_upper:
            continue
            
        # Handle CREATE DEFAULT
        if 'CREATE DEFAULT' in line_upper:
            output_lines.append('-- ' + line.rstrip() + ' (PostgreSQL: use DEFAULT in column definition)')
            continue
        
        # Handle CREATE PROCEDURE - mark for manual review
        if 'CREATE PROCEDURE' in line_upper or 'CREATE PROC' in line_upper:
            in_procedure = True
            output_lines.append('-- TODO: STORED PROCEDURE - Requires manual conversion to PostgreSQL function')
            output_lines.append('-- ' + line.rstrip())
            continue
            
        if in_procedure:
            output_lines.append('-- ' + line.rstrip())
            continue
        
        # Process line
        converted = line
        
        # Convert brackets to quotes
        converted = re.sub(r'\[(\w+)\]', r'"\1"', converted)
        
        # Data types
        converted = re.sub(r'\buniqueidentifier\b', 'uuid', converted, flags=re.I)
        converted = re.sub(r'\bdatetime2\b', 'timestamp', converted, flags=re.I)
        converted = re.sub(r'\bdatetime\b', 'timestamp', converted, flags=re.I)
        converted = re.sub(r'\bsmalldatetime\b', 'timestamp', converted, flags=re.I)
        converted = re.sub(r'\bnvarchar\b', 'varchar', converted, flags=re.I)
        converted = re.sub(r'\bnchar\b', 'char', converted, flags=re.I)
        converted = re.sub(r'\bntext\b', 'text', converted, flags=re.I)
        converted = re.sub(r'\bmoney\b', 'numeric(19,4)', converted, flags=re.I)
        converted = re.sub(r'\bbit\b', 'boolean', converted, flags=re.I)
        converted = re.sub(r'\bint\b', 'integer', converted, flags=re.I)
        converted = re.sub(r'\bimage\b', 'bytea', converted, flags=re.I)
        converted = re.sub(r'\bvarbinary\b', 'bytea', converted, flags=re.I)
        
        # Remove CLUSTERED/NONCLUSTERED
        converted = re.sub(r'\b(NON)?CLUSTERED\b', '', converted, flags=re.I)
        
        # Remove ASC/DESC in constraints
        converted = re.sub(r'\bASC\b', '', converted, flags=re.I)
        converted = re.sub(r'\bDESC\b', '', converted, flags=re.I)
        
        # Remove WITH clause (SQL Server index options)
        # Match )WITH (...) and everything up to optional ON [PRIMARY]
        converted = re.sub(
            r'\)\s*WITH\s*\([^)]+\)(\s*ON\s*"PRIMARY")?',
            ')',
            converted,
            flags=re.I
        )
        
        # Remove ON [PRIMARY] / ON "PRIMARY"
        converted = re.sub(r'\s*ON\s*"PRIMARY"\s*', ' ', converted, flags=re.I)
        
        # Fix CREATE TABLE - detect if line ends with just )
        if 'CREATE TABLE' in line_upper:
            in_create_table = True
            
        if in_create_table and converted.strip() == ')':
            converted = ');'
            in_create_table = False
        
        # ALTER TABLE fixes
        if line_upper.startswith('ALTER TABLE'):
            # WITH CHECK ADD -> ADD
            converted = re.sub(r'\bWITH CHECK ADD\b', 'ADD', converted, flags=re.I)
            
            # Add semicolon if missing
            if not converted.rstrip().endswith(';') and not converted.rstrip().endswith(','):
                if 'DEFAULT' in line_upper or 'CONSTRAINT' in line_upper:
                    # Check if next line is REFERENCES (FK continuation)
                    if i + 1 < len(lines) and 'REFERENCES' in lines[i+1].upper():
                        pass  # Don't add semicolon yet
                    else:
                        converted = converted.rstrip() + ';'
        
        # REFERENCES lines
        if 'REFERENCES' in line_upper and not line_upper.startswith('--'):
            if not converted.rstrip().endswith(';'):
                converted = converted.rstrip() + ';'
        
        # Functions
        converted = re.sub(r'\bISNULL\s*\(', 'COALESCE(', converted, flags=re.I)
        converted = re.sub(r'\bGETDATE\s*\(\)', 'CURRENT_TIMESTAMP', converted, flags=re.I)
        converted = re.sub(r'\bNEWID\s*\(\)', 'gen_random_uuid()', converted, flags=re.I)
        converted = re.sub(r'\bNEWSEQUENTIALID\s*\(\)', 'gen_random_uuid()', converted, flags=re.I)
        
        # TOP clause - comment it out as it needs manual placement
        if 'SELECT' in line_upper and 'TOP' in line_upper:
            converted = re.sub(
                r'\bTOP\s+\(?\d+\)?\s+PERCENT\b',
                '-- TODO: Remove TOP X PERCENT',
                converted,
                flags=re.I
            )
            converted = re.sub(
                r'\bTOP\s+\((\d+)\)',
                r'-- TODO: Add LIMIT \1 at end of query',
                converted,
                flags=re.I
            )
        
        # Only add non-empty lines
        converted = converted.rstrip()
        if converted:
            output_lines.append(converted)
    
    output_lines.append('')
    output_lines.append('COMMIT;')
    
    # Write output
    print(f"Writing to: {output_file}")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines))
    
    print("Conversion complete!")
    return True


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python convert_schema_v2.py input.sql output.sql")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    success = convert_sql_to_postgresql(input_file, output_file)
    sys.exit(0 if success else 1)
