//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCustomer
    {
        public System.Guid ArticleCustomerId { get; set; }
        public System.Guid ArticleId { get; set; }
        public System.Guid CustomerId { get; set; }
        public bool DefaultRec { get; set; }
        public string CustRef { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal FCLPrice { get; set; }
        public decimal LCLPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<System.DateTime> DateRevised { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual T_Currency T_Currency { get; set; }
    }
}
