//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleCustomer = new HashSet<ArticleCustomer>();
            this.ArticleKeyPicture = new HashSet<ArticleKeyPicture>();
            this.ArticlePackage = new HashSet<ArticlePackage>();
            this.ArticlePrice = new HashSet<ArticlePrice>();
            this.ArticleSupplier = new HashSet<ArticleSupplier>();
            this.OrderPKItems = new HashSet<OrderPKItems>();
            this.OrderQTItems = new HashSet<OrderQTItems>();
        }
    
        public System.Guid ArticleId { get; set; }
        public string SKU { get; set; }
        public string ArticleCode { get; set; }
        public string ArticleName { get; set; }
        public string ArticleName_Chs { get; set; }
        public string ArticleName_Cht { get; set; }
        public System.Guid CategoryId { get; set; }
        public Nullable<System.Guid> AgeGradingId { get; set; }
        public Nullable<System.Guid> ColorId { get; set; }
        public Nullable<System.Guid> OriginId { get; set; }
        public string Remarks { get; set; }
        public string ColorPattern { get; set; }
        public string Barcode { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleCustomer> ArticleCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleKeyPicture> ArticleKeyPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePackage> ArticlePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePrice> ArticlePrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleSupplier> ArticleSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPKItems> OrderPKItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTItems> OrderQTItems { get; set; }
        public virtual T_AgeGrading T_AgeGrading { get; set; }
        public virtual T_Category T_Category { get; set; }
        public virtual T_Color T_Color { get; set; }
        public virtual T_Currency T_Currency { get; set; }
        public virtual T_Origin T_Origin { get; set; }
    }
}
