//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlePackage
    {
        public System.Guid ArticlePackageId { get; set; }
        public System.Guid ArticleId { get; set; }
        public System.Guid PackageId { get; set; }
        public bool DefaultRec { get; set; }
        public Nullable<System.Guid> UomId { get; set; }
        public decimal InnerBox { get; set; }
        public decimal OuterBox { get; set; }
        public decimal CUFT { get; set; }
        public decimal SizeLength_in { get; set; }
        public decimal SizeWidth_in { get; set; }
        public decimal SizeHeight_in { get; set; }
        public decimal SizeLength_cm { get; set; }
        public decimal SizeWidth_cm { get; set; }
        public decimal SizeHeight_cm { get; set; }
        public decimal WeightGross_lb { get; set; }
        public decimal WeightNet_lb { get; set; }
        public decimal WeightGross_kg { get; set; }
        public decimal WeightNet_kg { get; set; }
        public decimal ContainerQty { get; set; }
        public string ContainerSize { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual T_Package T_Package { get; set; }
        public virtual T_UnitOfMeasures T_UnitOfMeasures { get; set; }
    }
}
