//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ArticleCustomer = new HashSet<ArticleCustomer>();
            this.CustomerAddress = new HashSet<CustomerAddress>();
            this.CustomerContact = new HashSet<CustomerContact>();
            this.OrderIN = new HashSet<OrderIN>();
            this.OrderPK = new HashSet<OrderPK>();
            this.OrderPL = new HashSet<OrderPL>();
            this.OrderQT = new HashSet<OrderQT>();
            this.OrderSC = new HashSet<OrderSC>();
            this.OrderSP = new HashSet<OrderSP>();
        }
    
        public System.Guid CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string ACNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerName_Chs { get; set; }
        public string CustomerName_Cht { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public Nullable<System.Guid> TermsId { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal CreditLimit { get; set; }
        public int ProfitMargin { get; set; }
        public bool BlackListed { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleCustomer> ArticleCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContact> CustomerContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderIN> OrderIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPK> OrderPK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPL> OrderPL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQT> OrderQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSC> OrderSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSP> OrderSP { get; set; }
        public virtual T_Currency T_Currency { get; set; }
        public virtual T_PaymentTerms T_PaymentTerms { get; set; }
        public virtual T_Region T_Region { get; set; }
    }
}
