//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public System.Guid CustomerContactId { get; set; }
        public System.Guid CustomerId { get; set; }
        public bool DefaultRec { get; set; }
        public Nullable<System.Guid> SalutationId { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> JobTitleId { get; set; }
        public Nullable<System.Guid> Phone1_Label { get; set; }
        public string Phone1_Text { get; set; }
        public Nullable<System.Guid> Phone2_Label { get; set; }
        public string Phone2_Text { get; set; }
        public Nullable<System.Guid> Phone3_Label { get; set; }
        public string Phone3_Text { get; set; }
        public Nullable<System.Guid> Phone4_Label { get; set; }
        public string Phone4_Text { get; set; }
        public Nullable<System.Guid> Phone5_Label { get; set; }
        public string Phone5_Text { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Z_JobTitle Z_JobTitle { get; set; }
        public virtual Z_Salutation Z_Salutation { get; set; }
    }
}
