//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQTSupplier
    {
        public System.Guid OrderQtSupplierId { get; set; }
        public System.Guid OrderQTItemId { get; set; }
        public string SuppRef { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal FCLCost { get; set; }
        public decimal LCLCost { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual OrderQTItems OrderQTItems { get; set; }
        public virtual T_Currency T_Currency { get; set; }
    }
}
