//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSCItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSCItems()
        {
            this.OrderINItems = new HashSet<OrderINItems>();
            this.OrderPCItems = new HashSet<OrderPCItems>();
        }
    
        public System.Guid OrderSCItemsId { get; set; }
        public System.Guid OrderSCId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid OrderQTItemId { get; set; }
        public decimal QtyOrdered { get; set; }
        public decimal QtyIN { get; set; }
        public decimal QtyOUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderINItems> OrderINItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPCItems> OrderPCItems { get; set; }
        public virtual OrderQTItems OrderQTItems { get; set; }
        public virtual OrderSC OrderSC { get; set; }
    }
}
