//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderQT()
        {
            this.OrderQTItems = new HashSet<OrderQTItems>();
        }
    
        public System.Guid OrderQTId { get; set; }
        public string QTNumber { get; set; }
        public Nullable<System.DateTime> QTDate { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid StaffId { get; set; }
        public int PriceMethod { get; set; }
        public decimal FCLFactor { get; set; }
        public decimal LCLFactor { get; set; }
        public string Unit { get; set; }
        public string Measurement { get; set; }
        public decimal SampleQty { get; set; }
        public int InputMask { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<System.Guid> TermsId { get; set; }
        public decimal Repayment { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalQtyIN { get; set; }
        public decimal TotalQtyOUT { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public int Revision { get; set; }
        public bool InUse { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<System.DateTime> AccessedOn { get; set; }
        public Nullable<System.Guid> AccessedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTItems> OrderQTItems { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual T_Currency T_Currency { get; set; }
        public virtual T_PaymentTerms T_PaymentTerms { get; set; }
    }
}
