//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQTItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderQTItems()
        {
            this.OrderPLItems = new HashSet<OrderPLItems>();
            this.OrderQTCustShipping = new HashSet<OrderQTCustShipping>();
            this.OrderQTPackage = new HashSet<OrderQTPackage>();
            this.OrderQTSupplier = new HashSet<OrderQTSupplier>();
            this.OrderQTSuppShipping = new HashSet<OrderQTSuppShipping>();
            this.OrderSCItems = new HashSet<OrderSCItems>();
            this.OrderSPItems = new HashSet<OrderSPItems>();
        }
    
        public System.Guid OrderQTItemId { get; set; }
        public System.Guid OrderQTId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid ArticleId { get; set; }
        public Nullable<System.Guid> PackageId { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public string Particular { get; set; }
        public string CustRef { get; set; }
        public Nullable<int> PriceType { get; set; }
        public decimal FactoryCost { get; set; }
        public decimal Margin { get; set; }
        public decimal FCL { get; set; }
        public decimal LCL { get; set; }
        public decimal SampleQty { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public int Carton { get; set; }
        public string GLAccount { get; set; }
        public string RefDocNo { get; set; }
        public string ShippingMark { get; set; }
        public decimal QtyIN { get; set; }
        public decimal QtyOUT { get; set; }
    
        public virtual Article Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPLItems> OrderPLItems { get; set; }
        public virtual OrderQT OrderQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTCustShipping> OrderQTCustShipping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTPackage> OrderQTPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTSupplier> OrderQTSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTSuppShipping> OrderQTSuppShipping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSCItems> OrderSCItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSPItems> OrderSPItems { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual T_Package T_Package { get; set; }
    }
}
