//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQTSuppShipping
    {
        public System.Guid OrderQTSuppShippingId { get; set; }
        public System.Guid OrderQTItemId { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public decimal QtyOrdered { get; set; }
        public decimal QtyShipped { get; set; }
        public int Status { get; set; }
    
        public virtual OrderQTItems OrderQTItems { get; set; }
    }
}
