//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPKItems
    {
        public System.Guid OrderPKItemsId { get; set; }
        public System.Guid OrderPKId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid ArticleId { get; set; }
        public System.Guid PackageId { get; set; }
        public int Sample { get; set; }
        public string CustRef { get; set; }
        public decimal InnerBox { get; set; }
        public decimal OuterBox { get; set; }
        public decimal Volumn { get; set; }
        public decimal UnitCost { get; set; }
        public decimal FCost { get; set; }
        public decimal Margin { get; set; }
        public decimal FCL { get; set; }
        public decimal LCL { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual OrderPK OrderPK { get; set; }
        public virtual T_Package T_Package { get; set; }
    }
}
