//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPK()
        {
            this.OrderPKItems = new HashSet<OrderPKItems>();
        }
    
        public System.Guid OrderPKId { get; set; }
        public string PKNumber { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid StaffId { get; set; }
        public decimal FCLFactor { get; set; }
        public decimal LCLFactor { get; set; }
        public string Unit { get; set; }
        public string Measurement { get; set; }
        public int InputMask { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public string PaymentTerms { get; set; }
        public decimal Repayment { get; set; }
        public bool InUse { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> AccessedDate { get; set; }
        public string AccessedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public int Revision { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPKItems> OrderPKItems { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual T_Currency T_Currency { get; set; }
    }
}
