//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderINShipment
    {
        public System.Guid OrderINShipmentId { get; set; }
        public System.Guid OrderINItemsId { get; set; }
        public int ShipmentID { get; set; }
        public decimal Qty { get; set; }
    
        public virtual OrderINItems OrderINItems { get; set; }
    }
}
