//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSP()
        {
            this.OrderSPItems = new HashSet<OrderSPItems>();
        }
    
        public System.Guid OrderSPId { get; set; }
        public string SPNumber { get; set; }
        public Nullable<System.DateTime> SPDate { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid StaffId { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalQtyIN { get; set; }
        public decimal TotalQtyOUT { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        public int Revision { get; set; }
        public bool InUse { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<System.DateTime> AccessedOn { get; set; }
        public Nullable<System.Guid> AccessedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSPItems> OrderSPItems { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
