//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSPItems
    {
        public System.Guid OrderSPItemsId { get; set; }
        public System.Guid OrderSPId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid OrderQTItemId { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
    
        public virtual OrderQTItems OrderQTItems { get; set; }
        public virtual OrderSP OrderSP { get; set; }
    }
}
