//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPC()
        {
            this.OrderPCItems = new HashSet<OrderPCItems>();
        }
    
        public System.Guid OrderPCId { get; set; }
        public string PCNumber { get; set; }
        public Nullable<System.DateTime> PCDate { get; set; }
        public System.Guid SupplierId { get; set; }
        public System.Guid StaffId { get; set; }
        public string YourRef { get; set; }
        public string Carrier { get; set; }
        public Nullable<System.Guid> PaymentTerms { get; set; }
        public Nullable<System.Guid> PricingTerms { get; set; }
        public Nullable<System.Guid> LoadingPort { get; set; }
        public Nullable<System.Guid> DischargePort { get; set; }
        public Nullable<System.Guid> Destination { get; set; }
        public Nullable<System.Guid> OriginId { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public int Revision { get; set; }
        public bool InUse { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<System.DateTime> AccessedOn { get; set; }
        public Nullable<System.Guid> AccessedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPCItems> OrderPCItems { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual T_Origin T_Origin { get; set; }
    }
}
