//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPCItems
    {
        public System.Guid OrderPCItemsId { get; set; }
        public System.Guid OrderPCId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid OrderSCItemsId { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyIN { get; set; }
        public decimal QtyOUT { get; set; }
    
        public virtual OrderPC OrderPC { get; set; }
        public virtual OrderSCItems OrderSCItems { get; set; }
    }
}
