//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderINCharges
    {
        public System.Guid OrderINChargeId { get; set; }
        public System.Guid OrderINId { get; set; }
        public System.Guid ChargeId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    
        public virtual OrderIN OrderIN { get; set; }
        public virtual T_Charge T_Charge { get; set; }
    }
}
