//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPLItems
    {
        public System.Guid OrderPLItemsId { get; set; }
        public System.Guid OrderPLId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid OrderQTItemId { get; set; }
    
        public virtual OrderPL OrderPL { get; set; }
        public virtual OrderQTItems OrderQTItems { get; set; }
    }
}
