//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderINItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderINItems()
        {
            this.OrderINShipment = new HashSet<OrderINShipment>();
        }
    
        public System.Guid OrderINItemsId { get; set; }
        public System.Guid OrderINId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.Guid OrderSCItemsId { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyIN { get; set; }
        public decimal QtyOUT { get; set; }
        public string ShippingMark { get; set; }
    
        public virtual OrderIN OrderIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderINShipment> OrderINShipment { get; set; }
        public virtual OrderSCItems OrderSCItems { get; set; }
    }
}
