//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AgeGrading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AgeGrading()
        {
            this.Article = new HashSet<Article>();
            this.T_AgeGrading1 = new HashSet<T_AgeGrading>();
        }
    
        public System.Guid AgeGradingId { get; set; }
        public Nullable<System.Guid> ParentAgeGrading { get; set; }
        public string AgeGradingCode { get; set; }
        public string AgeGradingName { get; set; }
        public string AgeGradingName_Chs { get; set; }
        public string AgeGradingName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AgeGrading> T_AgeGrading1 { get; set; }
        public virtual T_AgeGrading T_AgeGrading2 { get; set; }
    }
}
