//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BarCode
    {
        public System.Guid BarcodeId { get; set; }
        public string BarcodeCode { get; set; }
        public string BarcodeName { get; set; }
        public string BarcodeName_Chs { get; set; }
        public string BarcodeName_Cht { get; set; }
        public string BarcodeType { get; set; }
    }
}
