//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Category()
        {
            this.Article = new HashSet<Article>();
        }
    
        public System.Guid CategoryId { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string CategoryName_Chs { get; set; }
        public string CategoryName_Cht { get; set; }
        public int CostingMethod { get; set; }
        public int InventoryMethod { get; set; }
        public string TaxMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        public virtual T_Class T_Class { get; set; }
        public virtual T_Dept T_Dept { get; set; }
    }
}
