//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Charge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Charge()
        {
            this.OrderINCharges = new HashSet<OrderINCharges>();
            this.T_Charge1 = new HashSet<T_Charge>();
        }
    
        public System.Guid ChargeId { get; set; }
        public Nullable<System.Guid> ParentCharge { get; set; }
        public string ChargeCode { get; set; }
        public string ChargeName { get; set; }
        public string ChargeName_Chs { get; set; }
        public string ChargeName_Cht { get; set; }
        public string ACCode { get; set; }
        public string DCCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderINCharges> OrderINCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Charge> T_Charge1 { get; set; }
        public virtual T_Charge T_Charge2 { get; set; }
    }
}
