//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_City
    {
        public System.Guid CityId { get; set; }
        public System.Guid CountryId { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public string CityCode { get; set; }
        public string CityPhoneCode { get; set; }
        public string CityName { get; set; }
        public string CityName_Chs { get; set; }
        public string CityName_Cht { get; set; }
    
        public virtual T_Country T_Country { get; set; }
        public virtual T_Province T_Province { get; set; }
    }
}
