//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Color
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Color()
        {
            this.Article = new HashSet<Article>();
            this.T_Color1 = new HashSet<T_Color>();
        }
    
        public System.Guid ColorId { get; set; }
        public Nullable<System.Guid> ParentColor { get; set; }
        public string ColorCode { get; set; }
        public string ColorName { get; set; }
        public string ColorName_Chs { get; set; }
        public string ColorName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Color> T_Color1 { get; set; }
        public virtual T_Color T_Color2 { get; set; }
    }
}
