//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Group()
        {
            this.Staff = new HashSet<Staff>();
            this.T_Group1 = new HashSet<T_Group>();
        }
    
        public System.Guid GroupId { get; set; }
        public Nullable<System.Guid> ParentGroup { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public string GroupName_Chs { get; set; }
        public string GroupName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Group> T_Group1 { get; set; }
        public virtual T_Group T_Group2 { get; set; }
    }
}
