//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentTerms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PaymentTerms()
        {
            this.Customer = new HashSet<Customer>();
            this.OrderQT = new HashSet<OrderQT>();
            this.Supplier = new HashSet<Supplier>();
            this.T_PaymentTerms1 = new HashSet<T_PaymentTerms>();
        }
    
        public System.Guid TermsId { get; set; }
        public Nullable<System.Guid> ParentTerms { get; set; }
        public string TermsType { get; set; }
        public string TermsCode { get; set; }
        public string TermsName { get; set; }
        public string TermsName_Chs { get; set; }
        public string TermsName_Cht { get; set; }
        public int CreditDays { get; set; }
        public bool MonthlyAC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQT> OrderQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PaymentTerms> T_PaymentTerms1 { get; set; }
        public virtual T_PaymentTerms T_PaymentTerms2 { get; set; }
    }
}
