//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Package()
        {
            this.ArticlePackage = new HashSet<ArticlePackage>();
            this.OrderPKItems = new HashSet<OrderPKItems>();
            this.OrderQTItems = new HashSet<OrderQTItems>();
            this.T_Package1 = new HashSet<T_Package>();
        }
    
        public System.Guid PackageId { get; set; }
        public Nullable<System.Guid> ParentPackage { get; set; }
        public string PackageCode { get; set; }
        public string PackageName { get; set; }
        public string PackageName_Chs { get; set; }
        public string PackageName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePackage> ArticlePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPKItems> OrderPKItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQTItems> OrderQTItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Package> T_Package1 { get; set; }
        public virtual T_Package T_Package2 { get; set; }
    }
}
