//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Port
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Port()
        {
            this.T_Port1 = new HashSet<T_Port>();
        }
    
        public System.Guid PortId { get; set; }
        public Nullable<System.Guid> ParentPort { get; set; }
        public string PortCode { get; set; }
        public string PortName { get; set; }
        public string PortName_Chs { get; set; }
        public string PortName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Port> T_Port1 { get; set; }
        public virtual T_Port T_Port2 { get; set; }
    }
}
