//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Remarks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Remarks()
        {
            this.T_Remarks1 = new HashSet<T_Remarks>();
        }
    
        public System.Guid RemarkId { get; set; }
        public Nullable<System.Guid> ParentRemark { get; set; }
        public string RemarkCode { get; set; }
        public string RemarkName { get; set; }
        public string RemarkName_Chs { get; set; }
        public string RemarkName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Remarks> T_Remarks1 { get; set; }
        public virtual T_Remarks T_Remarks2 { get; set; }
    }
}
