//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ShippingMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ShippingMark()
        {
            this.T_ShippingMark1 = new HashSet<T_ShippingMark>();
        }
    
        public System.Guid ShippingMarkId { get; set; }
        public Nullable<System.Guid> ParentShippingMark { get; set; }
        public string ShippingMarkCode { get; set; }
        public string ShippingMarkName { get; set; }
        public string ShippingMarkName_Chs { get; set; }
        public string ShippingMarkName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ShippingMark> T_ShippingMark1 { get; set; }
        public virtual T_ShippingMark T_ShippingMark2 { get; set; }
    }
}
