//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnitOfMeasures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_UnitOfMeasures()
        {
            this.ArticlePackage = new HashSet<ArticlePackage>();
        }
    
        public System.Guid UomId { get; set; }
        public string UomCode { get; set; }
        public string UomName { get; set; }
        public string UomName_Chs { get; set; }
        public string UomName_Cht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePackage> ArticlePackage { get; set; }
    }
}
