//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDisplayPreference
    {
        public System.Guid PreferenceId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> PreferenceObjectId { get; set; }
        public string MetadataXml { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
