//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_AppPath
    {
        public System.Guid AppPathId { get; set; }
        public string Program { get; set; }
        public string Picture { get; set; }
        public string Report { get; set; }
        public string AppData { get; set; }
    }
}
