//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Counter
    {
        public System.Guid CounterId { get; set; }
        public Nullable<int> NextSuppCode { get; set; }
        public Nullable<int> NextStaffCode { get; set; }
        public Nullable<int> NextCustCode { get; set; }
        public Nullable<int> NextSKUCode { get; set; }
        public Nullable<int> NextArticleCode { get; set; }
        public Nullable<int> NextQTNumber { get; set; }
        public Nullable<int> NextPLNumber { get; set; }
        public Nullable<int> NextSCNumber { get; set; }
        public Nullable<int> NextPCNumber { get; set; }
        public Nullable<int> NextINNumber { get; set; }
        public Nullable<int> NextPKNumber { get; set; }
        public Nullable<int> NextSPNumber { get; set; }
    }
}
