//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_EventLog
    {
        public System.Guid EventId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EventCode { get; set; }
        public string EventLog { get; set; }
    }
}
