//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xPort5Entities : DbContext
    {
        public xPort5Entities()
            : base("name=xPort5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleCustomer> ArticleCustomer { get; set; }
        public virtual DbSet<ArticleKeyPicture> ArticleKeyPicture { get; set; }
        public virtual DbSet<ArticlePackage> ArticlePackage { get; set; }
        public virtual DbSet<ArticlePrice> ArticlePrice { get; set; }
        public virtual DbSet<ArticleSupplier> ArticleSupplier { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddress { get; set; }
        public virtual DbSet<CustomerContact> CustomerContact { get; set; }
        public virtual DbSet<OrderIN> OrderIN { get; set; }
        public virtual DbSet<OrderINCharges> OrderINCharges { get; set; }
        public virtual DbSet<OrderINItems> OrderINItems { get; set; }
        public virtual DbSet<OrderINShipment> OrderINShipment { get; set; }
        public virtual DbSet<OrderPC> OrderPC { get; set; }
        public virtual DbSet<OrderPCItems> OrderPCItems { get; set; }
        public virtual DbSet<OrderPK> OrderPK { get; set; }
        public virtual DbSet<OrderPKItems> OrderPKItems { get; set; }
        public virtual DbSet<OrderPL> OrderPL { get; set; }
        public virtual DbSet<OrderPLItems> OrderPLItems { get; set; }
        public virtual DbSet<OrderQT> OrderQT { get; set; }
        public virtual DbSet<OrderQTCustShipping> OrderQTCustShipping { get; set; }
        public virtual DbSet<OrderQTItems> OrderQTItems { get; set; }
        public virtual DbSet<OrderQTPackage> OrderQTPackage { get; set; }
        public virtual DbSet<OrderQTSupplier> OrderQTSupplier { get; set; }
        public virtual DbSet<OrderQTSuppShipping> OrderQTSuppShipping { get; set; }
        public virtual DbSet<OrderSC> OrderSC { get; set; }
        public virtual DbSet<OrderSCItems> OrderSCItems { get; set; }
        public virtual DbSet<OrderSP> OrderSP { get; set; }
        public virtual DbSet<OrderSPItems> OrderSPItems { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffAddress> StaffAddress { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierAddress> SupplierAddress { get; set; }
        public virtual DbSet<SupplierContact> SupplierContact { get; set; }
        public virtual DbSet<SystemInfo> SystemInfo { get; set; }
        public virtual DbSet<T_AgeGrading> T_AgeGrading { get; set; }
        public virtual DbSet<T_BarCode> T_BarCode { get; set; }
        public virtual DbSet<T_Category> T_Category { get; set; }
        public virtual DbSet<T_Charge> T_Charge { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_Class> T_Class { get; set; }
        public virtual DbSet<T_Color> T_Color { get; set; }
        public virtual DbSet<T_Country> T_Country { get; set; }
        public virtual DbSet<T_Currency> T_Currency { get; set; }
        public virtual DbSet<T_Dept> T_Dept { get; set; }
        public virtual DbSet<T_Division> T_Division { get; set; }
        public virtual DbSet<T_Group> T_Group { get; set; }
        public virtual DbSet<T_Origin> T_Origin { get; set; }
        public virtual DbSet<T_Package> T_Package { get; set; }
        public virtual DbSet<T_PaymentTerms> T_PaymentTerms { get; set; }
        public virtual DbSet<T_Port> T_Port { get; set; }
        public virtual DbSet<T_Province> T_Province { get; set; }
        public virtual DbSet<T_Region> T_Region { get; set; }
        public virtual DbSet<T_Remarks> T_Remarks { get; set; }
        public virtual DbSet<T_ShippingMark> T_ShippingMark { get; set; }
        public virtual DbSet<T_UnitOfMeasures> T_UnitOfMeasures { get; set; }
        public virtual DbSet<UserDisplayPreference> UserDisplayPreference { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<X_AppPath> X_AppPath { get; set; }
        public virtual DbSet<X_Counter> X_Counter { get; set; }
        public virtual DbSet<X_ErrorLog> X_ErrorLog { get; set; }
        public virtual DbSet<X_EventLog> X_EventLog { get; set; }
        public virtual DbSet<Z_Address> Z_Address { get; set; }
        public virtual DbSet<Z_Email> Z_Email { get; set; }
        public virtual DbSet<Z_JobTitle> Z_JobTitle { get; set; }
        public virtual DbSet<Z_Phone> Z_Phone { get; set; }
        public virtual DbSet<Z_Salutation> Z_Salutation { get; set; }
    }
}
