//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Email
    {
        public System.Guid EmailId { get; set; }
        public string EmailCode { get; set; }
        public string EmailName { get; set; }
        public string EmailName_Chs { get; set; }
        public string EmailName_Cht { get; set; }
    }
}
