//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPort5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Phone
    {
        public System.Guid PhoneId { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneName { get; set; }
        public string PhoneName_Chs { get; set; }
        public string PhoneName_Cht { get; set; }
    }
}
